### PR TITLE
Added g:colorscheme_primary_disable_italic

### PR DESCRIPTION
**Pull request by rbtnn**

### CODE REVIEW

**Comment by LisieRae** [comment]
Thanks for contributing. Just a few thoughts:
- What's the objection to italics? Just stylistic preference?
- Any reason for the long variable name? Maybe something more concise without the # character would be easier.
- Good catch on the loop variable (s:term).

**Comment by rbtnn** [comment]
> Any reason for the long variable name?

If it's a short variable name, there is a possibility that it conflicts with a variable name of other plugin. Therefore it's better to name a variable name as a prefix.

**Comment by rbtnn** [comment]
> What's the objection to italics? Just stylistic preference?

I recognize that there are a few person who doesn't like italic font on Vim. I don't like italic font on Vim too.

**Comment by rbtnn** [comment]
> Maybe something more concise without the # character would be easier.

I think  `g:vim_colorscheme_primary#disable_italic` or `g:vim_colorscheme_primary_disable_italic` is better than a short name.

**Comment by dbarnett** [comment]
The name `vim_colorscheme_primary#disable_italic` is treated as an autoload variable and will actually cause vim to search for a file called vim_colorscheme_primary.vim:
```
Searching for "/home/dbarnett/.vim/autoload/vim_colorscheme_primary.vim"
Searching for "/home/dbarnett/.vim/vim-addons/UltiSnips/autoload/vim_colorscheme_primary.vim"
Searching for "/home/dbarnett/.vim/vim-addons/vinegar/autoload/vim_colorscheme_primary.vim"
Searching for "/home/dbarnett/.vim/vim-addons/github-ynkdir-vim-vimlparser/autoload/vim_colorscheme_primary.vim"
…
Searching for "/home/dbarnett/.vim/after/autoload/vim_colorscheme_primary.vim"
not found in 'runtimepath': "autoload/vim_colorscheme_primary.vim"
```

In other google vim projects we use maktaba flags so the names don't conflict with other plugins (configured using [Glaive](https://github.com/google/vim-glaive)). Otherwise a variable name like `g:colorscheme_primary_disable_italic` would be reasonable.

**Comment by rbtnn** [comment]
@dbarnett I got it. So I think using `g:colorscheme_primary_disable_italic`. Is this OK?

**Comment by LisieRae** [comment]
Looks great. Thanks for the contribution! I'm sure the italically disinclined appreciate your improvement.

**Pull request merged**
